CREATE USER user1 IDENTIFIED BY  'pass111';
CREATE USER user2 IDENTIFIED BY 'pass222';
CREATE DATABASE mydb;

GRANT ALL PRIVILEGES ON mydb.* TO user1;
GRANT SELECT,UPDATE, INSERT, DELETE ON mydb.* TO user2;

SELECT user FROM mysql.user;
SHOW DATABASES;

ALTER USER user1 IDENTIFIED BY   '111';
ALTER USER user2 IDENTIFIED BY   '222';
