CREATE USER user1 WITH PASSWORD '123';
CREATE USER user2 WITH PASSWORD '456';
CREATE DATABASE mydb;

GRANT ALL PRIVILEGES ON DATABASE mydb TO user1;
GRANT CONNECT ON DATABASE mydb TO user2;

GRANT USAGE ON  SCHEMA public  TO user2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user2;

SELECT datname FROM pg_database;
SELECT usename FROM pg_user;

ALTER USER user1 WITH PASSWORD '1234';
ALTER USER user2 WITH PASSWORD '4567';
